---
title: "My First Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row #Page orientation. See note below on "height" vs "width" for row/column orientations
    vertical_layout: fill #Use "scroll" to change page to scrolling. With fill, page fits everything as use changes page size. I like fill :)
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
data(mtcars)
```

Column {data-height=400}
#Use "height" when page orientation is Row and "width" when page orientation is Column
-----------------------------------------------------------------------
#Using dash after the text ambove activates a new row/column (depending on what's specified above)

### Chart A

```{r}
ggplot(mtcars,aes(x=wt,y=mpg))+geom_point()
```

Column {data-height=200}
-----------------------------------------------------------------------

### Chart B

```{r}
ggplot(mtcars,aes(x=cyl))+geom_bar()

```

Column {data-height=200}
-----------------------------------------------------------------------

### Chart C

```{r}
ggplot(mtcars,aes(y=hp))+geom_boxplot()
```
Column {data-height=200}
-----------------------------------------------------------------------

### Chart D

```{r}
ggplot(mtcars,aes(y=hp))+geom_boxplot()
```

#Publish on the RPubs website using the Publish button in the visualization output